name: notebook
channels:
  - conda-forge
  - pytorch

dependencies:
  # AI/ML packages for workshop
  - llama-cpp-python
  - huggingface_hub

  - pip:
      - transformers>=4.39
      - openai>=1.0
      - anthropic>=0.8
      - python-dotenv
      - langchain>=0.1
      - sentence-transformers
